name: Count Files

on:
  push:
    branches:
      - main

jobs:
  count:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Count Files
        id: count_files
        run: echo "::set-output name=count::$(find . -type f \( ! -iname 'README.md' ! -path './.github/*' ! -path './.gitignore' \) | wc -l)"

      - name: Create Badge
        id: create_badge
        run: echo "::set-output name=badge::![File Count](https://img.shields.io/badge/dynamic/json?color=blue&label=files&query=\$.count&url=https%3A%2F%2Fapi.countapi.xyz%2Fget%2Fsachiniyer%2Frepo-files-counter%2Fcount)"

      - name: Update README
        run: |
          sed -i 's/!\\[File Count\\](.*)/$(echo "${{ steps.create_badge.outputs.badge }}")/' README.md
